# UTF-8, CRLF line endings
version: 1

global_settings:                         # ustawienia globalne, dotyczące wszystkich
  number_of_people: 99                 # liczba osób w symulacji
  simulation:
    start_month: JANUARY                 # pierwszy miesiąc symulacji
    start_year: 2020                     # rok początku symulacji
    end_month: DECEMBER                      # ostatni miesiąc symulacji
    end_year: 2020                      # rok zakończenia symulacji
    date_probability_bonuses:            # zdarzenia w których jest większe prawopodobieństwo na pójście do sklepu
      - from: 10.04.2020                # od 10.04.2020 do 15.04.2020 prawdopodobieństwo pójścia do sklepu
        to: 15.04.2020                   # jest 10 razy większe (0.05 x 10 = 0.5).
        probability_multipliers:         # A prawdopodobieństwo kupienia przedmiotu jest 5 razy większe
          go_to_shop: 5                 # Analogicznie w zdarzeniu poniżej
          buy_item: 5
      - from: 20.12.2020                 # od 10.04.2020 do 15.04.2020 prawdopodobieństwo pójścia do sklepu
        to: 31.12.2020                   # jest 10 razy większe (0.05 x 10 = 0.5).
        probability_multipliers:         # A prawdopodobieństwo kupienia przedmiotu jest 5 razy większe
          go_to_shop: 2                 # Analogicznie w zdarzeniu poniżej
          buy_item: 1
      - from: 20.12.2021
        to: 31.12.2021
        probability_multipliers:
          go_to_shop: 4
          buy_item: 2
      - from: 05.05.2021
        to: 05.05.2021
        probability_multipliers:
          go_to_shop: 4
          buy_item: 2


    needs_associations:
      - items_from_category: TELEWIZORY
        are: HIGHLY_ASSOCIATED
        with: UCHWYTY-TV
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.8
      - items_from_category: TELEWIZORY
        are: LOOSELY_ASSOCIATED
        with: KONSOLE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.2
      - items_from_category: TELEWIZORY
        are: ASSOCIATED
        with: NETFLIX
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.6
      - items_from_category: TELEWIZORY
        are: ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: TELEWIZORY
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3

 ####################################################3
      - items_from_category: LODÓWKI
        are: LOOSELY_ASSOCIATED
        with: ZMYWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.6
      - items_from_category: LODÓWKI
        are: LOOSELY_ASSOCIATED
        with: PRALKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.8
      - items_from_category: LODÓWKI
        are: HIGHLY_ASSOCIATED
        with: AKCESORIA-LODÓWKI
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: LODÓWKI
        are: ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: LODÓWKI
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
 #######################################
      - items_from_category: PRALKI
        are: LOOSELY_ASSOCIATED
        with: ZMYWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.6
      - items_from_category: PRALKI
        are: LOOSELY_ASSOCIATED
        with: LODÓWKA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.8
      - items_from_category: PRALKI
        are: ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: PRALKI
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
#######################
      - items_from_category: MIKROFALÓWKI
        are: ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: MIKROFALÓWKI
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: KUCHENKI
        are: ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: KUCHENKI
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: KUCHENKI
        are: ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: KUCHENKI
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTFONY-DO-600
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTFONY-DO-600
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-DO-600
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-DO-600
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTFONY-DO-600
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-DO-600
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTFONY-OD-600-DO-2K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTFONY-OD-600-DO-2K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-600-DO-2K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-600-DO-2K
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTFONY-OD-600-DO-2K
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-600-DO-2K
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTFONY-OD-2K-DO-4K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTFONY-OD-2K-DO-4K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-2K-DO-4K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-2K-DO-4K
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTFONY-OD-2K-DO-4K
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-2K-DO-4K
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTFONY-OD-4K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTFONY-OD-4K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-4K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-4K
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTFONY-OD-4K
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTFONY-OD-4K
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: IPHONE-DO-3K
        are: HIGHLY_ASSOCIATED
        with: IPHONE-KABLE
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: IPHONE-DO-3K
        are: HIGHLY_ASSOCIATED
        with: SMARTWATCHE-APPLE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPHONE-DO-3K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPHONE-DO-3K
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: IPHONE-DO-3K
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPHONE-DO-3K
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: IPHONE-OD-3K
        are: HIGHLY_ASSOCIATED
        with: IPHONE-KABLE
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: IPHONE-OD-3K
        are: HIGHLY_ASSOCIATED
        with: SMARTWATCHE-APPLE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPHONE-OD-3K
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPHONE-OD-3K
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: IPHONE-OD-3K
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPHONE-OD-3K
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: IPADY
        are: HIGHLY_ASSOCIATED
        with: IPHONE-KABLE
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: IPADY
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-ŁADOWARKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPADY
        are: ASSOCIATED
        with: POWERBANKI
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: IPADY
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: IPADY
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTWATCHE
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTWATCHE
        are: ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTWATCHE
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTWATCHE
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTWATCHE-PREMIUM
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTWATCHE-PREMIUM
        are: ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTWATCHE-PREMIUM
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTWATCHE-PREMIUM
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################
      - items_from_category: SMARTWATCHE-PREMIUM
        are: HIGHLY_ASSOCIATED
        with: SMARTFONY-KABLE-MICRO-USB
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.8
      - items_from_category: SMARTWATCHE-PREMIUM
        are: ASSOCIATED
        with: SMARTFONY-KABLE-TYP-C
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
      - items_from_category: SMARTWATCHE-PREMIUM
        are: HIGHLY_ASSOCIATED
        with: PRZEDŁUŻONA-GWARANCJA
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.5
      - items_from_category: SMARTWATCHE-PREMIUM
        are: ASSOCIATED
        with: UBEZPIECZENIE
        by_relation: ONE_TO_ONE
        with_buy_probability: 0.3
########################



      - items_from_category: FRIDGE
        are: LOOSELY_ASSOCIATED
        with: WASHING_MACHINE
        with_need_probability: 0.2
        with_buy_probability: 0.6

# Highly associate - main product requires associated one to be functional
# Associated - associated product is frequently used with the main one, but it's not required for main one to be functional
# Loosely associated - associated product is not used with main one at all but sometimes they are bought together. For example if people are buying AGD for brand new flat
profiles:                                # ustawienia profili, dotyczące określonej części ludzi
  - name: GRUPA1                           # nazwa grupy (klasy spolecznej)
    percent_of_people: 20                # jaki procent całości stanowi dana grupa
    daily_go_to_shop_probability: 0.05   # prawdopodobieństwo, że osoba pójdzie do sklepu danego dnia
    initial_account_balance: 1000         # Kwota, którą osoba ma na start
    salary:                              # kwota (zawieraca sie w przedziale from-to) jaką osoba odkłada pierwszego dnia każdego miesiąca na poniższe potrzeby
      from: 1000
      to: 2000
    needs:                               # potrzeby
      - category: TELEWIZORY                 # 60% na kupno przedmiotu z kategorii lodówka (pod warunkiem że pójdzie do sklepu. Patrz daily_go_to_shop_probability)
        num_of_items: 2                   # liczba przedmiotów do kupienia
        priority: 1                       # priorytet kupna (najmniejsza liczba ma największy priorytet)
        buy_probability: 0.6            # prawdopodobieństwo kupna (jeśli pójdzie do sklepu)
      - category: SŁUCHAWKI                # 50% na kupno przedmiotu z kategorii telewizory (jak wyżej)
        num_of_items: 2                   # ilość przedmiotów z kategorii
        priority: 2
        buy_probability: 0.4
      - category: SŁUCHAWKI                # 50% na kupno przedmiotu z kategorii telewizory (jak wyżej)
        num_of_items: 2                   # ilość przedmiotów z kategorii
        priority: 2
        buy_probability: 0.4              # 0% na kupienie niczego
      - category: SŁUCHAWKI                # 50% na kupno przedmiotu z kategorii telewizory (jak wyżej)
        num_of_items: 2                   # ilość przedmiotów z kategorii
        priority: 2
        buy_probability: 0.4              # 0% na kupienie niczego
      - category: SŁUCHAWKI                # 50% na kupno przedmiotu z kategorii telewizory (jak wyżej)
        num_of_items: 2                   # ilość przedmiotów z kategorii
        priority: 2
        buy_probability: 0.4              # 0% na kupienie niczego
      - category: SŁUCHAWKI                # 50% na kupno przedmiotu z kategorii telewizory (jak wyżej)
        num_of_items: 2                   # ilość przedmiotów z kategorii
        priority: 2
        buy_probability: 0.4              # 0% na kupienie niczego


  - name: GRUPA2                   # nazwa grupy (klasy spolecznej)
    percent_of_people: 60                # jaki procent całości stanowi dana grupa
    daily_go_to_shop_probability: 0.05   # prawdopodobieństwo, że osoba pójdzie do sklepu danego dnia
    initial_account_balance: 2000
    salary:                              # kwota (zawieraca sie w przedziale from-to) jaką osoba odkłada pierwszego dnia każdego miesiąca na poniższe potrzeby
      from: 3000
      to: 5000
    needs:                               # potrzeby
      - category: GAME_CONSOLE           # 80% na kupno kosnoli (pod warunkiem pójścia do sklepu)
        num_of_items: 2
        priority: 1
        buy_probability: 0.4

  - name: GRUPA3                       # nazwa grupy (klasy spolecznej)
    percent_of_people: 20                # jaki procent całości stanowi dana grupa
    daily_go_to_shop_probability: 0.05   # prawdopodobieństwo, że osoba pójdzie do sklepu danego dnia
    initial_account_balance: 3000       # Kwota, którą osoba ma na start
    salary:                              # kwota (zawieraca sie w przedziale from-to) jaką osoba odkłada pierwszego dnia każdego miesiąca na poniższe potrzeby
      from: 10000
      to: 15000
    needs:                               # potrzeby
      - category: GAME_CONSOLE           # 100 % na kupno konsoli (pod warunkiem że pójdzie do sklepu)
        num_of_items: 1
        priority: 1
        buy_probability: 0.4
                                         # 0% na kupno niczego (napewno coś kupi)

# NOTKA 1: Pensja jest losowana dla każdego na początku symulacji i pozostaje taka sama przez całą symulację
# NOTKA 2: Jeśli dojdzie do decyzji kupna przedmiotu, konkretny produkt wybierany jest losowo spośród produktów
#          mieszczących się w budżecie