# UTF-8, CRLF line endings

# Wersja struktury pliku konfiguracyjnego, która zapobiega wczytaniu pliku konfiguracyjnego
# w strukturze nieoczekiwanej przez program.
# Wersja pliku powinna być podbijana po zmianach w strukturze konfiguracji
# Wersja wspierana przez program określana jest w matrix.py::YMLConfiguration
version: 1

# Opcje globalne, niezależne od profilu
global_settings:

  # Maksymalna liczba osób symulacji. Na jej podstawie ustalana jest liczność grup profilowych (patrz Profile::percent_of_people)
  number_of_people: 1000

  # Opcje symulacji wspólne dla wszystkich osób w symulacji
  simulation:

    # Miesiąc i rok rozpoczęcia symulacji (symulacja rozpocznie się od pierwszego dnia miesiąca)
    start_month: JANUARY
    start_year: 2020

    # Miesiąc i rok zakończenia symulacji (symulacja zakończy się ostatniego dnia danego miesiąca)
    end_month: DECEMBER
    end_year: 2021


    # Lista przedziałów czasowych od-do ze zwiększonym prawdopodobieństwem pójścia na zakupy/kupna przedmiotu
    date_probability_bonuses:

        # Data od-do (from-to) w którym obowiązuje bonus prawdopodobieństwa.
      - from: 10.04.2020
        to: 15.04.2020

        # Mnożniki prawdopodobieństwa
        # go_to_shop: n1 -> zwiększa prawdopodobieństwo pójścia do sklepu każdego dnia z bonusem n1 razy
        # buy_item: n2 -> zwiększa prawdopodobieństwo, że podczas rozważań kupna przedmiotu osoba się na niego zdecyduje n2 razy
        # gdzie n1 i n2 to liczby całkowite lub rzeczywiste większe od 0
        probability_multipliers:
          go_to_shop: 5
          buy_item: 5

      - from: 20.12.2020
        to: 31.04.2020
        probability_multipliers:
          go_to_shop: 2
          buy_item: 1.2

      - from: 20.12.2021
        to: 31.12.2021
        probability_multipliers:
          go_to_shop: 4.58
          buy_item: 2.01

      - from: 05.05.2020
        to: 05.05.2021
        probability_multipliers:
          go_to_shop: 4.0
          buy_item: 2

      # ... więcej bonusów

    # Powiązania pomiędzy kategoriami przedmiotów
    # Powiązanie możemy rozumieć jako jednostronną relację A => B, gdzie A i B są kategoriami przedmiotów dostępnych w sklepie
    # Dostępne są 3 rodzaje powiązań:
    #   HIGHLY_ASSOCIATED (silnie powiązane) - kupno przedmiotu z kat. B jest rozważane natychmiast po zakupie przedmiotu z kat. A. Generuje reguły asocjacyjne
    #     Relację tę można rozumieć jako przedmioty które są niezbędne dla siebie nawzajem do bycia funkcjonalnymi
    #     Zazwyczaj są one umiejscowione blisko siebie na półkach w sklepie
    #   ASSOCIATED (powiązanie) - kupno przedmiotu z kat. B jest rozważane na końcu zakupów danego dnia. Generuje reguły asocjacyjne
    #     Relację tę można rozumieć jako przedmioty które często są używane ze sobą, lecz nie są one niezbędne dla siebie nawzajem do bycia funkcjonalnymi
    #     Symbolizują one propozycje pracownika sklepu proponującego dodatkowe powiązane rzeczy z oferty
    #   LOOSELY_ASSOCIATED (luźno powiązane) - typ powiązania znacznie różniący się od powyższych. Powiązania tego typu
    #     generują reguły sekwencyjne. Przedmiot z kat. B ma jedynie wspólną nadkategorie z przedmiotem z kat. A.
    #     Symbolizują one propozycje marketingowe przesłane do klienta po zakupach (SMS, EMAIL), dlatego zawierają dodatkowo określoną
    #     właściwość prawdopodobieństwa (with_need_probability) symbolizujące szanse na "złapanie przynęty" przez klienta
    #     Jeżeli klient kupi przedmiot z kategorii A, do 7miu dni symulacji otrzyma on propozycję marketingową z przedmiotami z
    #     kat. B, jeśli złapie przynętę, kat. B zostanie dodana do jego listy potrzeb (patrz Profile::needs)
    needs_associations:

      - items_from_category: WIRELESS-GAMEPAD
        are: HIGHLY_ASSOCIATED
        with: BATTERIES
        # relacja - określana jedynie dla powiązań HIGHLY_ASSOCIATED i ASSOCIATED. Wpływa na to czy klient potrzebuje dany produkt.
        #   np. GAMEPAD bezprzewodowy i baterie to powiązanie ONE_TO_ONE ponieważ każdy pad potrzebuje swoich baterii
        by_relation: ONE_TO_ONE
        # prawodopodobieństwo kupna powiązanego przedmiotu
        with_buy_probability: 0.8

      - items_from_category: TV
        are: ASSOCIATED
        with: NETFLIX_SUB
        # jak wyżej. Subskrybcja netflix nie jest potrzebna dla każdego telewizora - wystarczy jedna na wiele telewizorów
        by_relation: ONE_TO_MANY
        with_buy_probability: 0.5

      - items_from_category: FRIDGE
        are: LOOSELY_ASSOCIATED
        with: WASHING_MACHINE
        # prawdopodobieństwo "złapania przynęty"
        with_need_probability: 0.2
        # prawdopodobieństwo kupna przedmiotu pod warunkiem, że "przynęta zostanie złapana"
        with_buy_probability: 0.6

# Definicja profili (grup) klientów
# percent_of_people wszystkich grup powinien sumować się do 100
profiles:

    # Nazwa grupy
  - name: GRUPA1

    # Liczność grupy w procencie wszystkich (num_of_people z global_settings)
    percent_of_people: 20

    # Prawdopodobieństwo pójscia do sklepu każdego dnia
    daily_go_to_shop_probability: 0.05

    # Początkowy stan konta klientów grupy
    initial_account_balance: 1000

    # Przedział wypłaty od-do (from-to) dla danej grupy. Pieniądze wypłacane są pierwszego dnia każdego miesiąca symulacji
    salary:
      from: 1000
      to: 2000


    # Potrzeby klientów z grupy
    needs:

        # Kategoria przedmiotu
      - category: FRIDGE
        # Liczba potrzebnych przedmiotów
        num_of_items: 1
        # Priorytet na liście zakupów (im mniejsza liczba tym większy priorytet, możliwe ujemne)
        priority: 1
        # Prawdopodobieństwo kupna przedmiotu pod warunkiem pójścia do sklepu i posiadania odpowiedniej kwoty na koncie
        buy_probability: 0.6

      - category: TV
        num_of_items: 2
        priority: 2
        buy_probability: 0.4

      # ... więcej potrzeb

  - name: GRUPA2
    percent_of_people: 60
    daily_go_to_shop_probability: 0.05
    initial_account_balance: 2000
    salary:
      from: 3000
      to: 5000
    needs:
      - category: GAME_CONSOLE
        num_of_items: 2
        priority: 1
        buy_probability: 0.4

  - name: GRUPA3
    percent_of_people: 20
    daily_go_to_shop_probability: 0.05
    initial_account_balance: 3000
    salary:
      from: 10000
      to: 15000
    needs:
      - category: GAME_CONSOLE
        num_of_items: 1
        priority: 1
        buy_probability: 0.4

  # ... więcej grup