global_settings:                         # ustawienia globalne, dotyczące wszystkich
  number_of_people: 1000                 # liczba osób w symulacji
  simulation:
    start_month: JANUARY                 # pierwszy miesiąc symulacji
    end_month: JUNE                      # ostatni miesiąc symulacji
    year: 2020                           # rok symulacji
    date_probability_bonus:              # zdarzenia w których jest większe prawopodobieństwo na pójście do sklepu
      - from: 10.04                      # od 10.04.2020 do 15.04.2020 prawdopodobieństwo pójścia do sklepu
        to: 15.04                        # jest 10 razy większe (0.05 x 10 = 0.5).
        probability_multipliers:         # A prawdopodobieństwo kupienia przedmiotu jest 5 razy większe
          go_to_shop: 10                 # Analogicznie w zdarzeniu poniżej
          buy_item: 5

      - from: 05.05
        to: 05.05
        probability_multipliers:
          go_to_shop: 4
          buy_item: 2
    needs_associations:
      - need: WIRELESS-GAMEPAD
        associated_with: BATTERIES
        association_type: HIGHLY_ASSOCIATED # think about batteries every time when put pad to cart. If has money buy with 0.8 prob
        relation: ONE_FOR_ONE # relation BATTERIES -> GAMEPAD. For example Netflix could be ONE_TO_MANY. it's about cancel proposition because person already has something
        buy_probability: 0.8 # probability he needs batteries
      - need: TV
        associated_with: NETFLIX_SUB
        association_type: ASSOCIATED # it's proposed by shop before finalization
        relation: ONE_TO_MANY # if person have netflix, he doesn't need more
        buy_probability: 0.5
      - need: FRIDGE
        associated_with: WASHING_MACHINE
        association_type: LOOSELY_ASSOCIATED # it's proposed after purchase somehow. For ex. SMS, EMAIL. It increases go_to_shop probability for defined time
        relation: NONE
        bonus_in_days: 14

# Highly associate - main product requires associated one to be functional
# Associated - associated product is frequently used with the main one, but it's not required for main one to be functional
# Loosely associated - associated product is not used with main one at all but sometimes they are bought together. For example if people are buying AGD for brand new flat
profiles:                                # ustawienia profili, dotyczące określonej części ludzi
  - name: POOR                           # nazwa grupy (klasy spolecznej)
    percent_of_people: 20                # jaki procent całości stanowi dana grupa
    daily_go_to_shop_probability: 0.05   # prawdopodobieństwo, że osoba pójdzie do sklepu danego dnia
    initial_account_balance: 1000
    salary:                              # kwota (zawieraca sie w przedziale from-to) jaką osoba odkłada pierwszego dnia każdego miesiąca na poniższe potrzeby
      from: 1000
      to: 2000
    needs:                               # potrzeby
      - category: FRIDGE                 # 60% na kupno przedmiotu z kategorii lodówka (pod warunkiem że pójdzie do sklepu. Patrz daily_go_to_shop_probability)
        num_of_items: 1
        priority: 1
        buy_probability: 0.6
      - category: TV                     # 50% na kupno przedmiotu z kategorii telewizory (jak wyżej)
        num_of_items: 2
        priority: 2
        buy_probability: 0.4
                                         # 0% na kupienie niczego (jak wyżej)

  - name: MIDDLE_CLASS                   # nazwa grupy (klasy spolecznej)
    percent_of_people: 60                # jaki procent całości stanowi dana grupa
    daily_go_to_shop_probability: 0.05   # prawdopodobieństwo, że osoba pójdzie do sklepu danego dnia
    initial_account_balance: 2000
    salary:                              # kwota (zawieraca sie w przedziale from-to) jaką osoba odkłada pierwszego dnia każdego miesiąca na poniższe potrzeby
      from: 3000
      to: 5000
    needs:                               # potrzeby
      - category: GAME_CONSOLE           # 80% na kupno kosnoli (pod warunkiem pójścia do sklepu)
        num_of_items: 2
        priority: 1
        buy_probability: 0.4

  - name: RICH_MEN                       # nazwa grupy (klasy spolecznej)
    percent_of_people: 20                # jaki procent całości stanowi dana grupa
    daily_go_to_shop_probability: 0.05   # prawdopodobieństwo, że osoba pójdzie do sklepu danego dnia
    initial_account_balance: 3000
    salary:                              # kwota (zawieraca sie w przedziale from-to) jaką osoba odkłada pierwszego dnia każdego miesiąca na poniższe potrzeby
      from: 10000
      to: 15000
    needs:                               # potrzeby
      - category: GAME_CONSOLE           # 100 % na kupno konsoli (pod warunkiem że pójdzie do sklepu)
        num_of_items: 1
        priority: 1
        buy_probability: 0.4
                                         # 0% na kupno niczego (napewno coś kupi)

# NOTKA 1: Pensja jest losowana dla każdego na początku symulacji i pozostaje taka sama przez całą symulację
# NOTKA 2: Jeśli dojdzie do decyzji kupna przedmiotu, konkretny produkt wybierany jest losowo spośród produktów
#          mieszczących się w budżecie